before_script:
  - julia -e 'using InteractiveUtils;
              versioninfo()'

variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

stages:
  - test


## testing

.test_template: &test_template
  script:
    - mkdir $JULIA_DEPOT_PATH # Pkg3.jl#325
    - julia --project -e "using Pkg;
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.test(; coverage=true);"

test:v0.7:
  stage: test
  image: juliagpu/julia:v0.7-opencl
  <<: *test_template

test:v1.0:
  stage: test
  image: juliagpu/julia:v1.0-opencl
  <<: *test_template

test:dev:
  stage: test
  image: juliagpu/julia:dev-opencl
  <<: *test_template
  allow_failure: true
